### ISSUE TITLE
EdDSA tests

### ISSUE THREAD

**Issue by str4d** [google/wycheproof#5]
I would love to be able to run this against my [Java EdDSA library](https://github.com/str4d/ed25519-java), which implements the JCA and will have a Provider class in the next release. But we'd need the test cases first 😄

**Comment by thaidn** [comment]
Sorry for the long delay. @bleichen is looking into testing EdDSA and we'll have some update in upcoming weeks.

**Comment by bleichen** [comment]
I'm working on test vectors, though at this point extensive randomized testing still seems to be the most reliable method to find bugs. Since EdDSA does distinct operations for signing and verifying just signing and verifying random messages with random keys already covers a lot of code, in particular it covers point multiplication. From what I've seen so far point multiplication is where bugs are made.

One problem that is not covered by randomized testing is the generation of the point R.
Since EdDSA is deterministic this point is determined by the message and the key.
One danger is that an implementation might compute an incorrect point R', but generate a signature
that verifies. If the implementation is later corrected, the signature is recomputed with the correct R,
then it might be possible to leak information about the secret key.

**Comment by thaidn** [comment]
There are some EdDSA tests in https://github.com/google/wycheproof/blob/master/testvectors/eddsa_test.json.

Please reopen if you have any further questions or comments.

Cheers!
