### ISSUE TITLE
Are tcIds stable?

### ISSUE THREAD

**Issue by briansmith** [google/wycheproof#52]
Hi, are the tcId values within each file stable? For example, when I fix a bug in a library, would it make sense to reference the tcId and the filename of the test? Or do they get renumbered when they are updated?

**Comment by bleichen** [comment]
No. tcIds are not stable. They change every time the test vectors are generated and are only useful as identifier of a test vector if the version
of the test vectors is also known. There are no plans to make them stable. I.e. the test vector generation often sorts the test vectors by key so that vectors with the same key are in the same test group. So adding test vectors to one group, changes the tcIds in the next group.

For citing a test vector, it is probably reasonable to just copy the test vector.
For excluding test vectors with legacy behavior, I'm adding flags to the test vectors.
For documentation there are comments in the test vectors that can point to CVE or other
references.

**Comment by briansmith** [comment]
OK, thanks for the explanation.

> For citing a test vector, it is probably reasonable to just copy the test vector.

I understand that the test vectors aren't copyrightable and so the license doesn't apply to them. However, it would be great if that could be made explicit in the LICENSE file.

**Comment by thaidn** [comment]
The main question is answered, so I'm going to close this ticket.

**Comment by thaidn** [comment]
> I understand that the test vectors aren't copyrightable and so the license doesn't apply to them. However, it would be great if that could be made explicit in the LICENSE file.

(reopening this because this was discussed internally)

Hey Brian,

Just curious, why you think the test vectors are not copyrightable? Can you use them even if they are under the Apache 2 license? We want you to use them, but we're not sure if we can convince the lawyers to exclude the test vectors from the copyright notice.

**Comment by thaidn** [comment]
Friendly ping Brian.

**Comment by briansmith** [comment]
I am able to use the test vectors without any changes.

**Comment by thaidn** [comment]
Cool.
