### ISSUE TITLE
Flag "format" vs. "data" failures in testvectors

### ISSUE THREAD

**Issue by SalusaSecondus** [google/wycheproof#60]
For algorithms which take in an encoded object (such as (EC)DSA signatures) it would be helpful to flag those test cases which are wrong because the encoding is wrong rather than because the encoded data is wrong. This is partially done with the "BER" flag, but that only covers alternate (but still vaguely sane) encodings.

The specific use-case is I have some (EC)DSA logic I wish to test which takes in raw `(r,s)` values and thus it makes sense for me to simply skip any cases which do not test the underlying values/math. Instead, the various encoding related tests simply test my test-harness' parsing logic, which isn't helpful.

**Comment by bleichen** [comment]
I'm considering to add files with IEEE P1363 encoded signatures. These are fixed length encodings of r and s. There is also the webcrypto format which is similar.

I'm unsure whether raw r and s makes sense. The question is to find the boundaries in this case.
Libraries that allow arbitrary inputs (e.g. stuff written in javascript or python) are difficult to test in this way. For example a few years ago I found a ridiculous implementation in python, where any signatures
were easily forged by setting r=1 and s=0.5
The library would verify the signatures somewhat like this:
First check 0<r<q and 0<s<q, which of course passes.
Then compute the modular inverse of s. Because of lack of checks it would result in s^-1 mod q == 0.
Compute u1 = h(msg) * s^-1 mod q  (hence get u1 = 0)
Compute u2 = r * s^-1 mod q (hence get u2=0)
Compute v = g^u1 y^u2 mod p mod q (and get v = 1)
and finally verify v == r.

If the signatures are in a specific encoding then such examples can be tested if the encoding allows
such input (e.g. ASN does) or leave them out if the encoding does not support such things.
Generally the goal is to have test vectors that are close to the input formats that are actually used.

**Comment by thaidn** [comment]
Test vectors with P1363 encoded signatures were added.

Please reopen this ticket if you need more help or want to discuss this further.
