### ISSUE TITLE
Test case P-384/P-521 bug from golang

### ISSUE THREAD

**Issue by alex** [google/wycheproof#66]
https://github.com/golang/go/issues/29903, but no test case there :-) Hopefully one part of Google can talk to another.

**Comment by alex** [comment]
Awesome.

At the time I filed this I didn't even realize your team had found the bug, but chatting with Fillippo I gather the test case came from your work :-)

**Comment by thaidn** [comment]
Yeah the test case came from this project. Daniel Bleichenbacher created the test case, and another person ran it against Golang and found the bug.

**Comment by bleichen** [comment]
One issue here is that it took me some time to notice that there is already a published paper on the
attack. The golang bug is a special case of this paper.

Akishita T., Takagi T. (2003) Zero-Value Point Attacks on Elliptic Curve Cryptosystem. ISC 2003. LNCS 2851

Instead of just adding test vectors for the golang bug, I'm extending the the test vectors to include test cases for other similar situations, i.e. distinct curves, distinct point representations, distinct addition chains.

**Comment by thaidn** [comment]
The test cases that @bleichen mentioned above were added in https://github.com/google/wycheproof/commit/7c9c6db85cbdbb497b3cc07bf60acc8453088a39.
