### ISSUE TITLE
A few KW tests in v1 folder marked "acceptable" violate spec for minimum plaintext length

### ISSUE THREAD

**Issue by dspdon** [google/wycheproof#99]
I found 3 KW test cases in the newer "testvectors_v1" folder that need review of the "result" flag enumeration.  These test cases are in testvectors_v1/aes_wrap_test.json, test cases tcId 12, 54 and 109.  These test cases each violate the minimum required plaintext length for KW in SP 800-38F Sec 5.2, which states KW plaintext (i.e. the key to be wrapped) must be a minimum of 2 semiblocks in length (which is 16 bytes).  I believe these test cases should update the result flag from 'acceptable' to 'invalid'.

Relevant snippet from SP 800-38F Sec 5.2:  "KW-AE and TKW-AE are defined on two or more semiblocks."

**Comment by bleichenbacher-daniel** [comment]
NIST does indeed not define KEY_WRAP for short inputs. However RFC 3394 does that in Section 2. The difference leads to ambiguous definitions. Some comparisons are here:
https://github.com/google/wycheproof/blob/master/doc/key_wrap.md

Also when a test vector has ambiguous definitions (i.e. is "acceptable") then there should be a flag, which is described in the header of the test vector file. Some libraries do in fact implement the behavior from RFC 3394. In these cases it is important to test the correctness of the wrapped key, since short keys are a rather strange exception.

**Comment by dspdon** [comment]
Thanks Daniel, your explanation makes sense.  Closing the issue i created for KW and KWP would make sense, for the same reason you cite.
